import numpy as np

# Some colors
WHITE =     (255, 255, 255)
BLUE =      (  0,   0, 255)
GREEN =     (  0, 255,   0)
RED =       (255,   0,   0)
BLACK =     (0,   0,   0)
TEXTCOLOR = (  0,   0,  0)

# General game parameters
DELTA_T = 0.016
FPS = 60
WINDOW_W = 1500
WINDOW_H = 1000
WINDOW_SIZE = (WINDOW_W, WINDOW_H)
PLAYER1_POS = np.array([0.05*WINDOW_W, 0.05*WINDOW_H])
PLAYER2_POS = np.array([0.95*WINDOW_W, 0.95*WINDOW_H])
MIN_KEY_PRESS_DELAY = 250
HIT_ACTIVATION_DELAY = 250

# UFO parameters
UFO_RAD = 20
UFO_MASS = 30
UFO_ANGULAR_RESOLUTION = 5*np.pi/180
MIN_SHOT_POWER = 100
MAX_SHOT_POWER = 400
SHOT_POWER_INCREMENT = 20

# Projectile parameters
PROJECTILE_RAD = 5
PROJECTILE_MASS = 10

# General physics parameters
G_CONST = 2

# Planet parameters
MIN_PLANET_RAD = 40
MAX_PLANET_RAD = 80
PLANET_DENSITY = 10
PLANET_MIN_SEPARATION = 100

# Wormhole parameters
WORMHOLE_DENSITY = PLANET_DENSITY
WORMHOLE_OUTER_RAD = 100
WORMHOLE_INNER_RAD = 0.7*WORMHOLE_OUTER_RAD
WORMHOLE_MIN_SEPARATION = PLANET_MIN_SEPARATION
TELEPORTATION_DELAY = 250
